# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Terminal_server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15Terminal_server.proto\x1a\x1bgoogle/protobuf/empty.proto\"2\n\x0cWellnessData\x12\x10\n\x08\x64\x61tetime\x18\x01 \x01(\t\x12\x10\n\x08wellness\x18\x02 \x01(\x02\"4\n\rPollutionData\x12\x10\n\x08\x64\x61tetime\x18\x01 \x01(\t\x12\x11\n\tpollution\x18\x02 \x01(\x02\"f\n\x0c\x43ompleteData\x12!\n\x08wellness\x18\x01 \x01(\x0b\x32\r.WellnessDataH\x00\x12#\n\tpollution\x18\x02 \x01(\x0b\x32\x0e.PollutionDataH\x00\x42\x0e\n\x0c\x43ompleteData2K\n\x10Terminal_service\x12\x37\n\x0csend_results\x12\r.CompleteData\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Terminal_server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WELLNESSDATA._serialized_start=54
  _WELLNESSDATA._serialized_end=104
  _POLLUTIONDATA._serialized_start=106
  _POLLUTIONDATA._serialized_end=158
  _COMPLETEDATA._serialized_start=160
  _COMPLETEDATA._serialized_end=262
  _TERMINAL_SERVICE._serialized_start=264
  _TERMINAL_SERVICE._serialized_end=339
# @@protoc_insertion_point(module_scope)
